name: lunar-e2e-463a879b21-hosted
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-463a879b21-hosted.yml
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      LUNAR_HUB_HOST: 37457647057-github-21-4c93254ef842.e2e.demo.earthly.dev
      LUNAR_HUB_GRPC_PORT: "443"
      LUNAR_HUB_HTTP_PORT: "443"
      LUNAR_HUB_INSECURE: "false"
      LUNAR_HUB_TOKEN: token
      LUNAR_STRICT_MODE: "true"
    steps:
      - uses: earthly/lunar-ci-tracer@v4.8.0
      - name: Action step
        uses: actions/github-script@v7
        with:
          script: core.info('action step')
      - name: Subdirectory action step
        uses: actions/cache/restore@v4
        with:
          path: .lunar-e2e-never-cached
          key: lunar-e2e-never-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Step number 1
        id: step-1
        run: |
          /bin/echo 'step 1 start'
          /bin/echo 'step 1 complete'
      - name: Step number 2
        id: step-2
        run: |
          /bin/echo 'step 2 start'
          /bin/echo 'step 2 middle'
          /bin/echo 'step 2 complete'
      - name: Step number 3
        id: step-3
        run: |
          /bin/echo 'step 3 start'
          /bin/echo 'step 3 middle'
          /bin/echo 'step 3 complete'
      - name: Step number 4
        id: step-4
        run: |
          /bin/echo 'step 4 start'
          /bin/echo 'step 4 complete'

