name: lunar-e2e-463a879b21
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-463a879b21.yml
jobs:
  e2e:
    runs-on: localdev-e2e-test-37457647057-1-github-21-e2e
    steps:
      - name: Action step
        uses: actions/github-script@v7
        with:
          script: core.info('action step')
      - name: Subdirectory action step
        uses: actions/cache/restore@v4
        with:
          path: .lunar-e2e-never-cached
          key: lunar-e2e-never-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Step number 1
        id: step-1
        run: |
          /bin/echo 'step 1 start'
          /bin/echo 'step 1 complete'
      - name: Step number 2
        id: step-2
        run: |
          /bin/echo 'step 2 start'
          /bin/echo 'step 2 middle'
          /bin/echo 'step 2 complete'
      - name: Step number 3
        id: step-3
        run: |
          /bin/echo 'step 3 start'
          /bin/echo 'step 3 middle'
          /bin/echo 'step 3 complete'
      - name: Step number 4
        id: step-4
        run: |
          /bin/echo 'step 4 start'
          /bin/echo 'step 4 complete'

