name: lunar-e2e-pin-rotation-701cfe083
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 701cfe083'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-701cfe083'
    runs-on: localdev-e2e-test-37456015413-1-github-3-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 701cfe083'
